---
- name: Get the desired package of flink.
  command: wget https://archive.apache.org/dist/flink/flink-{{ version }}/flink-{{ version }}-bin-hadoop2-scala_2.10.tgz
  become: true
  args:
    creates: flink-{{ version }}-bin-hadoop2-scala_2.10.tgz
- name: Unarchive a flink file that is already on the target  machine.
  unarchive:
    src: '{{ home_directory }}/flink-{{ version }}-bin-hadoop2-scala_2.10.tgz'
    dest: "{{ home_directory }}"
    remote_src: yes
